### ISSUE TITLE
Change the writing of external files by scantokens

### ISSUE THREAD

**Issue by pablgonz** [cgnieder/xsim#30] opened 2018-04-21 01:39 UTC
Hello, first of all, grateful for the great work with `xsim`, I have a suggestion (or idea) that I can maybe implement in `xsim`, I know that writing external files is necessary because of `verbatim` can not be used as an argument in macros, but, in some replies on [tex.sx](https://tex.stackexchange.com):

- [Collect contents of an environment (that contains verbatim content)](https://tex.stackexchange.com/a/373983)
- [understanding makeatletter with minted / minipage / colorboxes](https://tex.stackexchange.com/questions/328517/understanding-makeatletter-with-minted-minipage-colorboxesl)
- [Saving in macros plus \scantokens as an alternative to external files](https://tex.stackexchange.com/questions/97944/saving-in-macros-plus-scantokens-as-an-alternative-to-external-filesl)

and `pythontex` package, they manage not to use external files and save `verbatim` material using `scantokens`. Could you implement this in `xsim `?
Saludos

**Comment by cgnieder** [comment] 2018-06-09 10:19
I am planning to add a solution as an alternative to the current behavior (actually I was planning this from the start). I do not have as much time as I used to for (La)TeX currently.
This will come one time…

**Comment by cgnieder** [comment] 2019-10-06 10:37
I close this as a duplicate of issue #9

**Closed by cgnieder** 2019-10-06 10:37 UTC
Labels: duplicate, enhancement

**Comment by pablgonz** [comment] 2019-10-06 17:34
Hooo, I hadn't read [(#9)](https://github.com/cgnieder/xsim/issues/9) when I wrote this. I wrote a comment on the previous commit  [5ccf34d ](https://github.com/cgnieder/xsim/commit/5ccf34dbe0b490c4f0d57cdd8d9a4a3dc8aa68d7). Waiting for the new version :). Thank you for everything.
The best.
Pablo

**Comment by cgnieder** [comment] 2019-10-06 17:46
I have seen the comment and I've noticed the `scontents` package. For the time being the switching-off of the external files will disable using verbatim material, though… `scontents` does

    \NewDocumentCommand { \__scontents_verb_arg:w } { +v }

which is a little bit of cheating ;) `\NewDocumentCommand` is meant to define user commands while `\__scontents_verb_arg:w` clearly is an internal command for the package… I've misused `\NewDocumentCommand`, too, but not in `xsim` where I want to keep the code as clean as I can.

I might find another way, though :)

**Comment by pablgonz** [comment] 2019-10-06 18:11
Yes, the truth is that `\scontents_verb_arg:w` is a bit misleading ... there was no other way out since `\tl_rescan` does not work properly with `verbatim` material, only the old `\scantokens` has that ability :) (for now) . 

The code of `xsim` is pure and clear, we appreciate the comments you leave in source codes, otherwise I would never have understood how `xsimverb` worked. 

The comment left it for the `scontents` environment rather than for the `\Scontents` command, basically it is the same idea as `xsimverb`, but, saving the content in `\tl` and modifying the blessed end of line `^^M` :) (a headache) and stored this in a sequence.

With your new version I think I can move (at last) from `exsheets` to `xsim`.

Maybe an idea of the "star" type in environments not to write in external files?
Saludos
