### ISSUE TITLE
TikZ externalise causes XSIM to produce lots of extra files

### ISSUE THREAD

**Issue by zoqaeski** [cgnieder/xsim#32] opened 2018-05-16 13:45 UTC
I've got a document with exercises and lots of images which I'm externalising with TikZ to speed up compilation times. Due to some conflict between how `externalize` works and XSIM, my images directory is getting filled up with multiple copies of all the exercises—one set of all of them for each externalised image.

I've attached a working example to demonstrate; it's more of a maximal working example as I just made a subset of the aforementioned document.

The TikZ external system call expects a directory called `tikz` to exist in the same folder as the `github-xsim-bug.tex`, and to compile it you'll need to call `lualatex` once, followed by `make -f github-xsim-bug.makefile`, followed by a second `lualatex` invocation. The main file does compile with plain `pdflatex`, but the externalisation itself uses `luatex`. Once it's all compiled, you should get the main document, a set of images in `tikz/`, and a set of every exercise/solution pair for every image.

The TikZ `external/mode=list and make` is easier on my system's memory—and much quicker to compile—but commenting out line 43 will revert to the usual forking method using `-shell-escape` or `-write18`. Both methods still cause XSIM to spit out lots of additional files that are never actually used.

[github-xsim-bug.txt](https://github.com/cgnieder/xsim/files/2009302/github-xsim-bug.txt)
(Github wouldn't let me upload `*.tex` so I renamed it `*.txt`.)

**Comment by cgnieder** [comment] 2018-06-09 10:40
Please – can you reduce this to [a MWE](https://tex.meta.stackexchange.com/questions/228/)
(at max one or two exercises, no packages other than the ones needed to recreate the core issue)?

I'm not able to see any problems with the following example:

```latex
\documentclass{article}

\usepackage{tikz}
\usetikzlibrary{external}
\tikzexternalize
\usepackage{xsim}

\begin{document}

\begin{exercise}
  \begin{tikzpicture}
    \draw (0,0) -- (5,1) ;
  \end{tikzpicture}
\end{exercise}

\end{document}
```

**Comment by cgnieder** [comment] 2020-02-19 14:47
Referring to https://github.com/cgnieder/xsim/issues/32#issuecomment-396874149 I still see no difference. I compile it once with 

```latex
\usepackage{xsim}
```

and once with

```latex
\usepackage[no-files]{xsim}
```

and the difference is only the files produced this by `xsim` itself. I close this as it seems this is not a bug or issue in `xsim` itself.

**Closed by cgnieder** 2020-02-19 14:47 UTC
